name: Create Branch and Notify
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/josue

jobs:
  create-branch:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}
      
      - name: Create Josue branch
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          if ! git ls-remote --heads origin feature/josue | grep feature/josue > /dev/null; then
            git checkout -b feature/josue
            git push origin feature/josue
          fi

  setup-discord:
    if: github.ref == 'refs/heads/feature/josue'
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: npm install discord.js
        
      - name: Setup Discord Channel
        uses: actions/github-script@v6
        with:
          script: |
            const Discord = require('discord.js');
            const client = new Discord.Client({ 
              intents: [
                Discord.GatewayIntentBits.Guilds,
                Discord.GatewayIntentBits.GuildWebhooks
              ]
            });
            
            async function setup() {
              await client.login('${{ secrets.DISCORD_BOT_TOKEN }}');
              const guild = await client.guilds.fetch('${{ secrets.DISCORD_GUILD_ID }}');
              
              let category = guild.channels.cache.find(c => c.name === 'GitHub-Notifications');
              if (!category) {
                category = await guild.channels.create({
                  name: 'GitHub-Notifications',
                  type: Discord.ChannelType.GuildCategory
                });
              }
              
              let channel = guild.channels.cache.find(c => c.name === 'feature-josue');
              if (!channel) {
                channel = await guild.channels.create({
                  name: 'feature-josue',
                  type: Discord.ChannelType.GuildText,
                  parent: category.id
                });
              }
              
              const webhook = await channel.createWebhook({
                name: 'GitHub Notifications'
              });
              
              core.setOutput('webhook_url', webhook.url);
              core.setSecret(webhook.url);
            }
            
            setup();

  notify:
    needs: setup-discord
    if: github.ref == 'refs/heads/feature/josue'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Notify Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ steps.setup-discord.outputs.webhook_url }}
          DISCORD_TEMPLATE_PATH: "./discord-template.json"
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d @$DISCORD_TEMPLATE_PATH \
          $DISCORD_WEBHOOK_URL