name: Create Branch and Notify
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/josue

jobs:
  create-branch:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}
      
      - name: Create Josue branch
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          if ! git ls-remote --heads origin feature/josue | grep feature/josue > /dev/null; then
            git checkout -b feature/josue
            git push origin feature/josue
          fi

  setup-discord:
    if: github.ref == 'refs/heads/feature/josue'
    runs-on: ubuntu-latest
    outputs:
      webhook_url: ${{ steps.discord_setup.outputs.webhook_url }}
    steps:
      - name: Install Dependencies
        run: |
          npm init -y
          npm install discord.js@14.14.1 --no-save
        
      - name: Setup Discord Channel
        id: discord_setup
        uses: actions/github-script@v6
        with:
          script: |
            const { Client, GatewayIntentBits } = require('discord.js');
            const client = new Client({ 
              intents: [GatewayIntentBits.Guilds]
            });
            
            try {
              await client.login('${{ secrets.DISCORD_BOT_TOKEN }}');
              const guild = await client.guilds.fetch('${{ secrets.DISCORD_GUILD_ID }}');
              
              // Buscar canal existente
              const channels = await guild.channels.fetch();
              let channel = channels.find(c => c.name === 'github-notifications');
              
              // Solo crear si no existe
              if (!channel) {
                console.log('Creando nuevo canal github-notifications');
                channel = await guild.channels.create({
                  name: 'github-notifications',
                  type: 0
                });
              } else {
                console.log('Canal github-notifications encontrado');
              }
              
              // Buscar webhook existente
              const webhooks = await channel.fetchWebhooks();
              let webhook = webhooks.find(wh => wh.name === 'GitHub Notifications');
              
              // Solo crear webhook si no existe
              if (!webhook) {
                console.log('Creando nuevo webhook');
                webhook = await channel.createWebhook({
                  name: 'GitHub Notifications'
                });
              } else {
                console.log('Webhook existente encontrado');
              }
              
              core.setOutput('webhook_url', webhook.url);
              await client.destroy();
            } catch (error) {
              console.error('Error completo:', error);
              core.setFailed(`Error: ${error.message}`);
              if (client) await client.destroy();
            }

  notify:
    needs: setup-discord
    if: github.ref == 'refs/heads/feature/josue'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Get Changes
        id: changes
        run: |
          if git rev-parse HEAD~1 >/dev/null 2>&1; then
            echo "DIFF_FILES<<EOF" >> $GITHUB_ENV
            git diff --name-status HEAD~1 >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
            
            if [ -f index.html ]; then
              echo "INDEX_CHANGES<<EOF" >> $GITHUB_ENV
              git diff HEAD~1 index.html >> $GITHUB_ENV || echo "No hay cambios en index.html"
              echo "EOF" >> $GITHUB_ENV
            else
              echo "INDEX_CHANGES=No existe el archivo index.html" >> $GITHUB_ENV
            fi
          else
            echo "DIFF_FILES=Primer commit - no hay historial previo" >> $GITHUB_ENV
            echo "INDEX_CHANGES=Primer commit - no hay cambios para mostrar" >> $GITHUB_ENV
          fi

      - name: Notify Discord
        uses: up9cloud/action-notify@master
        env:
          GITHUB_JOB_STATUS: ${{ job.status }}
          DISCORD_WEBHOOK_URL: ${{ needs.setup-discord.outputs.webhook_url }}
          DISCORD_TEMPLATE_PATH: "./discord-template.json"
          STATUS_COLOR_SUCCESS: "#22863a"
          STATUS_COLOR_FAILURE: "#cb2431"
          STATUS_COLOR_CANCELLED: "#6a737d"
          STATUS_EMOJI_SUCCESS: "✅"
          STATUS_EMOJI_FAILURE: "❌"
          STATUS_EMOJI_CANCELLED: "⚪"
          DIFF_FILES: ${{ env.DIFF_FILES }}
          INDEX_CHANGES: ${{ env.INDEX_CHANGES }}